chance-per-efficiency-level: 0.0015
bite-chance:
    default: 0.002
    vip: 0.003
environmental:
    sunrise: true
    boat: true
    crowding: true
    mobs: true
    rain: true
    lightning: true
enchantments:
    efficiency: true
    looting: true
    fortune: true
    flame-aspect: true
    thorns: true