name: EnhancedFishing
main: com.norcode.bukkit.enhancedfishing.EnhancedFishing
version: 0.0.7
author: metalhedd
softdepend: [EnhancedFishingAnvilAddon]
commands:
    enhancedfishing:
        aliases: [efishing]
        usage: /<command> reload
        permission: enhancedfishing.admin
permissions:
    enhancedfishing.admin:
        description: Allows reloading config file with /efishing reload.
        default: op

    enhancedfishing.enchantment.*:
        description: All possible enchantments will affect the players fishing rods.
        default: true
        children:
            enhancedfishing.enchantment.efficiency: true
            enhancedfishing.enchantment.looting: true
            enhancedfishing.enchantment.fortune: true
            enhancedfishing.enchantment.thorns: true
            enhancedfishing.enchantment.fireaspect: true
            enhancedfishing.enchantment.power: true
