name: ${project.name}
main: ${project.main}
version: ${project.version}
author: ${project.authors}
commands:
    enhancedfishing:
        aliases: [efishing]
        usage: /<command> reload
        permission: enhancedfishing.admin
permissions:
    enhancedfishing.admin:
        description: Allows reloading config file with /efishing reload.
        default: op

    enhancedfishing.enchantment.*:
        description: All possible enchantments will affect the players fishing rods.
        default: true
        children:
            enhancedfishing.enchantment.efficiency: true
            enhancedfishing.enchantment.looting: true
            enhancedfishing.enchantment.fortune: true
            enhancedfishing.enchantment.thorns: true
            enhancedfishing.enchantment.fireaspect: true
            enhancedfishing.enchantment.power: true
